version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
        - checkout
        - run: python main.py
  test:
    docker:
      - image: cimg/base:current
    steps:
        - checkout
        - run: python tests.py
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build       
